"""empty message

Revision ID: d23fbb1fe2cc
Revises: a6cddbf4b93a
Create Date: 2023-12-28 13:44:58.266712

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d23fbb1fe2cc"
down_revision: Union[str, None] = "a6cddbf4b93a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmark", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookmark", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
